name: ⭐ Source Request
description: Request a new Source
title: "[Site Suggestion] "
labels: [Site request]
assignees: phisher98
body:

  - type: input
    id: name
    attributes:
      label: Source name
      placeholder: |
        Example: "Not Real Source"
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Source link
      placeholder: |
        Example: "https://notrealsource.org"
    validations:
      required: true

  - type: input
    id: language
    attributes:
      label: Source language
      placeholder: |
        Example: "Hindi"
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments.
        Example: "+18/NSFW = yes"

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your issue will be closed if you haven't done these steps.
      options:
        - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
          required: true
        - label: I have written a title with source name.
          required: true
        - label: I have checked that the extension does not already exist on the any Dev Repo or Request.
          required: true
        - label: I have checked that the extension does not already exist by searching on CS and verified it.
          required: true
        - label: I will fill out all of the requested information in this form.
          required: true
